services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - caddy
    volumes:
      - /home/math/infra-docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/math/infra-docker/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
    
networks:
  caddy:
    external: true