services:
  grimoire:
    image: goniszewski/grimoire:latest
    container_name: grimoire
    restart: unless-stopped
    environment:
      - PORT=5173
      - PUBLIC_HTTPS_ONLY=false
      - PUBLIC_SIGNUP_DISABLED=true
    volumes:
      - /home/math/docker-data/grimoire_data:/app/data/
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grimoire.rule=Host(`bookmarks.mathdesigns.app`)"
      - "traefik.http.routers.grimoire.entrypoints=websecure"
      - "traefik.http.routers.grimoire.tls.certresolver=production"  
    ports:
      - 5173:5173
    networks:
      - traefik_default
volumes:
  grimoire_data:
networks:
  traefik_default:
    external: true