services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8081
    volumes:
      - /home/math/infra-docker/qbittorrent:/config
      - /home/math/infra-docker/media/movies:/downloads/movies
      - /home/math/infra-docker/media/series:/downloads/series
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped