version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=REDACTED
      - ZONE=mathdesigns.app
      - SUBDOMAIN=
      - PROXIED=true