version: '3'
services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-vpn
    environment:
      - WG_HOST=REDACTED PUBLIC IP
      - PASSWORD=REDACTED
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=192.168.216.x # Replace x with your desired value
    ports:
      - "51820:51820/udp"
      - "51822:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
