version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - /home/math/docker-data/homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=8123"
      - "traefik.http.routers.homeassistant.rule=Host(`ha.mathdesigns.app`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls.certresolver=production"
    networks:
      - traefik_default
    ports:
      - 8123:8123
    privileged: true

networks:
  traefik_default:
    external: true
